node {
        stage('Checkout') {
            git url: 'https://github.com/pratibhaagrawal/APIProject.git',  branch: 'master'
            echo '****************CHECKOUT SUCCESSFUL****************'
        }
       

       
			
	stage('Build') {
		def mvn_version = 'Maven_Home'
		withEnv( ["PATH+MAVEN=${tool mvn_version}/bin"]) {
			bat 'mvn site'

			}
		}
}
